// Shared career metadata for the interactive map and detail pages
window.careersData = [
  { id: "accountant", name: "Accountant", medianSalary: 78000 },
  { id: "actuary", name: "Actuary", medianSalary: 115000 },
  { id: "administrative-assistant", name: "Administrative Assistant", medianSalary: 42000 },
  { id: "aerospace-engineer", name: "Aerospace Engineer", medianSalary: 130000 },
  { id: "air-traffic-controller", name: "Air Traffic Controller", medianSalary: 135000 },
  { id: "aircraft-mechanic", name: "Aircraft Mechanic", medianSalary: 75000 },
  { id: "analytical-chemist", name: "Analytical Chemist", medianSalary: 66000 },
  { id: "animator", name: "Animator", medianSalary: 78000 },
  { id: "anthropologist", name: "Anthropologist", medianSalary: 66000 },
  { id: "architect", name: "Architect", medianSalary: 90000 },
  { id: "architecture-drafter", name: "Architecture Drafter", medianSalary: 60000 },
  { id: "archivist", name: "Archivist", medianSalary: 54000 },
  { id: "art-director", name: "Art Director", medianSalary: 105000 },
  { id: "artist-fine", name: "Fine Artist", medianSalary: 58000 },
  { id: "astronomer", name: "Astronomer", medianSalary: 130000 },
  { id: "athletic-trainer", name: "Athletic Trainer", medianSalary: 54000 },
  { id: "audio-engineer", name: "Audio Engineer", medianSalary: 60000 },
  { id: "auto-mechanic", name: "Auto Mechanic", medianSalary: 48000 },
  { id: "baker", name: "Baker", medianSalary: 34000 },
  { id: "bank-teller", name: "Bank Teller", medianSalary: 36000 },
  { id: "barber", name: "Barber", medianSalary: 40000 },
  { id: "bartender", name: "Bartender", medianSalary: 33000 },
  { id: "biochemist", name: "Biochemist", medianSalary: 105000 },
  { id: "biomedical-engineer", name: "Biomedical Engineer", medianSalary: 95000 },
  { id: "book-editor", name: "Book Editor", medianSalary: 63000 },
  { id: "bricklayer", name: "Bricklayer", medianSalary: 54000 },
  { id: "budget-analyst", name: "Budget Analyst", medianSalary: 86000 },
  { id: "building-inspector", name: "Building Inspector", medianSalary: 68000 },
  { id: "bus-driver", name: "Bus Driver", medianSalary: 45000 },
  { id: "business-analyst", name: "Business Analyst", medianSalary: 90000 },
  { id: "business-owner-small", name: "Small Business Owner", medianSalary: 65000 },
  { id: "butcher", name: "Butcher", medianSalary: 38000 },
  { id: "cable-technician", name: "Cable Technician", medianSalary: 52000 },
  { id: "carpenter", name: "Carpenter", medianSalary: 56000 },
  { id: "cartographer", name: "Cartographer", medianSalary: 70000 },
  { id: "cashier", name: "Cashier", medianSalary: 29000 },
  { id: "chef", name: "Chef", medianSalary: 58000 },
  { id: "chemical-engineer", name: "Chemical Engineer", medianSalary: 115000 },
  { id: "chemist", name: "Chemist", medianSalary: 66000 },
  { id: "childcare-worker", name: "Childcare Worker", medianSalary: 30000 },
  { id: "chiropractor", name: "Chiropractor", medianSalary: 76000 },
  { id: "civil-engineer", name: "Civil Engineer", medianSalary: 97000 },
  { id: "claims-adjuster", name: "Claims Adjuster", medianSalary: 66000 },
  { id: "clinical-lab-technician", name: "Clinical Lab Technician", medianSalary: 57000 },
  { id: "coach-sports", name: "Sports Coach", medianSalary: 49000 },
  { id: "computer-hardware-engineer", name: "Computer Hardware Engineer", medianSalary: 132000 },
  { id: "computer-network-architect", name: "Network Architect", medianSalary: 126000 },
  { id: "computer-programmer", name: "Programmer", medianSalary: 95000 },
  { id: "construction-laborer", name: "Construction Laborer", medianSalary: 42000 },
  { id: "construction-manager", name: "Construction Manager", medianSalary: 105000 },
  { id: "consultant-management", name: "Management Consultant", medianSalary: 125000 },
  { id: "content-creator", name: "Content Creator", medianSalary: 50000 },
  { id: "cookie-decorator", name: "Cookie Decorator", medianSalary: 35000 },
  { id: "correctional-officer", name: "Correctional Officer", medianSalary: 52000 },
  { id: "cosmetologist", name: "Cosmetologist", medianSalary: 36000 },
  { id: "courier", name: "Courier", medianSalary: 38000 },
  { id: "court-reporter", name: "Court Reporter", medianSalary: 65000 },
  { id: "cryptographer", name: "Cryptographer", medianSalary: 140000 },
  { id: "customer-support-agent", name: "Customer Support Agent", medianSalary: 42000 },
  { id: "data-analyst", name: "Data Analyst", medianSalary: 82000 },
  { id: "data-engineer", name: "Data Engineer", medianSalary: 135000 },
  { id: "data-scientist", name: "Data Scientist", medianSalary: 140000 },
  { id: "database-administrator", name: "Database Administrator", medianSalary: 105000 },
  { id: "dental-assistant", name: "Dental Assistant", medianSalary: 43000 },
  { id: "dental-hygienist", name: "Dental Hygienist", medianSalary: 82000 },
  { id: "dentist", name: "Dentist", medianSalary: 160000 },
  { id: "detective", name: "Detective", medianSalary: 81000 },
  { id: "dietitian", name: "Dietitian", medianSalary: 68000 },
  { id: "dispatcher", name: "Dispatcher", medianSalary: 46000 },
  { id: "doctor-family", name: "Family Physician", medianSalary: 220000 },
  { id: "doctor-surgeon", name: "Surgeon", medianSalary: 330000 },
  { id: "dog-trainer", name: "Dog Trainer", medianSalary: 38000 },
  { id: "economist", name: "Economist", medianSalary: 115000 },
  { id: "editor-video", name: "Video Editor", medianSalary: 62000 },
  { id: "electrician", name: "Electrician", medianSalary: 60000 },
  { id: "elementary-teacher", name: "Elementary Teacher", medianSalary: 61000 },
  { id: "emt", name: "EMT", medianSalary: 42000 },
  { id: "environmental-engineer", name: "Environmental Engineer", medianSalary: 97000 },
  { id: "event-planner", name: "Event Planner", medianSalary: 54000 },
  { id: "farmer", name: "Farmer", medianSalary: 55000 },
  { id: "fashion-designer", name: "Fashion Designer", medianSalary: 78000 },
  { id: "financial-advisor", name: "Financial Advisor", medianSalary: 98000 },
  { id: "financial-analyst", name: "Financial Analyst", medianSalary: 90000 },
  { id: "firefighter", name: "Firefighter", medianSalary: 53000 },
  { id: "fitness-trainer", name: "Fitness Trainer", medianSalary: 46000 },
  { id: "flight-attendant", name: "Flight Attendant", medianSalary: 62000 },
  { id: "florist", name: "Florist", medianSalary: 34000 },
  { id: "food-scientist", name: "Food Scientist", medianSalary: 76000 },
  { id: "forensic-scientist", name: "Forensic Scientist", medianSalary: 68000 },
  { id: "frontend-developer", name: "Frontend Developer", medianSalary: 105000 },
  { id: "game-developer", name: "Game Developer", medianSalary: 100000 },
  { id: "genetic-counselor", name: "Genetic Counselor", medianSalary: 92000 },
  { id: "geographer", name: "Geographer", medianSalary: 86000 },
  { id: "geologist", name: "Geologist", medianSalary: 95000 },
  { id: "graphic-designer", name: "Graphic Designer", medianSalary: 56000 },
  { id: "groundskeeper", name: "Groundskeeper", medianSalary: 35000 },
  { id: "hair-stylist", name: "Hair Stylist", medianSalary: 38000 },
  { id: "healthcare-administrator", name: "Healthcare Administrator", medianSalary: 104000 },
  { id: "historian", name: "Historian", medianSalary: 66000 },
  { id: "home-health-aide", name: "Home Health Aide", medianSalary: 33000 },
  { id: "homicide-detective", name: "Homicide Detective", medianSalary: 85000 },
  { id: "hotel-manager", name: "Hotel Manager", medianSalary: 65000 },
  { id: "hr-manager", name: "HR Manager", medianSalary: 130000 },
  { id: "hvac-technician", name: "HVAC Technician", medianSalary: 58000 },
  { id: "illustrator", name: "Illustrator", medianSalary: 62000 },
  { id: "industrial-designer", name: "Industrial Designer", medianSalary: 76000 },
  { id: "industrial-engineer", name: "Industrial Engineer", medianSalary: 96000 },
  { id: "information-security-analyst", name: "Cybersecurity Analyst", medianSalary: 120000 },
  { id: "insurance-agent", name: "Insurance Agent", medianSalary: 58000 },
  { id: "interior-designer", name: "Interior Designer", medianSalary: 65000 },
  { id: "interpreter", name: "Interpreter", medianSalary: 52000 },
  { id: "investigator-private", name: "Private Investigator", medianSalary: 57000 },
  { id: "ironworker", name: "Ironworker", medianSalary: 58000 },
  { id: "it-support-specialist", name: "IT Support Specialist", medianSalary: 56000 },
  { id: "janitor", name: "Janitor", medianSalary: 33000 },
  { id: "journalist", name: "Journalist", medianSalary: 60000 },
  { id: "judge", name: "Judge", medianSalary: 200000 },
  { id: "lab-technician", name: "Lab Technician", medianSalary: 52000 },
  { id: "land-surveyor", name: "Land Surveyor", medianSalary: 67000 },
  { id: "landscaper", name: "Landscaper", medianSalary: 36000 },
  { id: "lawyer", name: "Lawyer", medianSalary: 145000 },
  { id: "librarian", name: "Librarian", medianSalary: 61000 },
  { id: "loan-officer", name: "Loan Officer", medianSalary: 63000 },
  { id: "logistician", name: "Logistician", medianSalary: 79000 },
  { id: "machinist", name: "Machinist", medianSalary: 52000 },
  { id: "maintenance-technician", name: "Maintenance Technician", medianSalary: 50000 },
  { id: "makeup-artist", name: "Makeup Artist", medianSalary: 62000 },
  { id: "management-analyst", name: "Management Analyst", medianSalary: 100000 },
  { id: "marine-biologist", name: "Marine Biologist", medianSalary: 72000 },
  { id: "marketing-manager", name: "Marketing Manager", medianSalary: 135000 },
  { id: "massage-therapist", name: "Massage Therapist", medianSalary: 48000 },
  { id: "mathematician", name: "Mathematician", medianSalary: 115000 },
  { id: "mechanical-engineer", name: "Mechanical Engineer", medianSalary: 100000 },
  { id: "medical-assistant", name: "Medical Assistant", medianSalary: 38000 },
  { id: "medical-scientist", name: "Medical Scientist", medianSalary: 105000 },
  { id: "meteorologist", name: "Meteorologist", medianSalary: 85000 },
  { id: "microbiologist", name: "Microbiologist", medianSalary: 76000 },
  { id: "midwife", name: "Midwife", medianSalary: 120000 },
  { id: "military-officer", name: "Military Officer", medianSalary: 80000 },
  { id: "model-fashion", name: "Fashion Model", medianSalary: 45000 },
  { id: "mortician", name: "Mortician", medianSalary: 60000 },
  { id: "motion-graphics-designer", name: "Motion Graphics Designer", medianSalary: 78000 },
  { id: "museum-curator", name: "Museum Curator", medianSalary: 61000 },
  { id: "music-producer", name: "Music Producer", medianSalary: 70000 },
  { id: "musician", name: "Musician", medianSalary: 55000 },
  { id: "network-engineer", name: "Network Engineer", medianSalary: 110000 },
  { id: "neurologist", name: "Neurologist", medianSalary: 290000 },
  { id: "nuclear-engineer", name: "Nuclear Engineer", medianSalary: 125000 },
  { id: "nuclear-technician", name: "Nuclear Technician", medianSalary: 85000 },
  { id: "nurse-practitioner", name: "Nurse Practitioner", medianSalary: 120000 },
  { id: "nutritionist", name: "Nutritionist", medianSalary: 63000 },
  { id: "occupational-therapist", name: "Occupational Therapist", medianSalary: 92000 },
  { id: "office-manager", name: "Office Manager", medianSalary: 62000 },
  { id: "oncologist", name: "Oncologist", medianSalary: 320000 },
  { id: "ophthalmologist", name: "Ophthalmologist", medianSalary: 300000 },
  { id: "optometrist", name: "Optometrist", medianSalary: 130000 },
  { id: "painter", name: "Painter", medianSalary: 44000 },
  { id: "paramedic", name: "Paramedic", medianSalary: 52000 },
  { id: "park-ranger", name: "Park Ranger", medianSalary: 50000 },
  { id: "paralegal", name: "Paralegal", medianSalary: 58000 },
  { id: "pathologist", name: "Pathologist", medianSalary: 270000 },
  { id: "personal-trainer", name: "Personal Trainer", medianSalary: 48000 },
  { id: "pharmacist", name: "Pharmacist", medianSalary: 128000 },
  { id: "photographer", name: "Photographer", medianSalary: 42000 },
  { id: "physical-therapist", name: "Physical Therapist", medianSalary: 98000 },
  { id: "physician-assistant", name: "Physician Assistant", medianSalary: 120000 },
  { id: "physicist", name: "Physicist", medianSalary: 140000 },
  { id: "pilot-commercial", name: "Commercial Pilot", medianSalary: 120000 },
  { id: "pipefitter", name: "Pipefitter", medianSalary: 63000 },
  { id: "plumber", name: "Plumber", medianSalary: 60000 },
  { id: "police-officer", name: "Police Officer", medianSalary: 65000 },
  { id: "political-scientist", name: "Political Scientist", medianSalary: 122000 },
  { id: "principal", name: "School Principal", medianSalary: 110000 },
  { id: "probation-officer", name: "Probation Officer", medianSalary: 54000 },
  { id: "product-manager", name: "Product Manager", medianSalary: 135000 },
  { id: "professor", name: "College Professor", medianSalary: 92000 },
  { id: "project-manager", name: "Project Manager", medianSalary: 100000 },
  { id: "psychologist", name: "Psychologist", medianSalary: 100000 },
  { id: "psychiatrist", name: "Psychiatrist", medianSalary: 280000 },
  { id: "public-relations-specialist", name: "PR Specialist", medianSalary: 68000 },
  { id: "quality-assurance-tester", name: "QA Tester", medianSalary: 65000 },
  { id: "radiologic-technologist", name: "Radiologic Technologist", medianSalary: 65000 },
  { id: "real-estate-agent", name: "Real Estate Agent", medianSalary: 60000 },
  { id: "real-estate-broker", name: "Real Estate Broker", medianSalary: 90000 },
  { id: "receptionist", name: "Receptionist", medianSalary: 36000 },
  { id: "registered-nurse", name: "Registered Nurse", medianSalary: 83000 },
  { id: "researcher-clinical", name: "Clinical Researcher", medianSalary: 95000 },
  { id: "restaurant-manager", name: "Restaurant Manager", medianSalary: 58000 },
  { id: "roofer", name: "Roofer", medianSalary: 46000 },
  { id: "safety-inspector", name: "Safety Inspector", medianSalary: 70000 },
  { id: "sales-manager", name: "Sales Manager", medianSalary: 140000 },
  { id: "sales-representative", name: "Sales Representative", medianSalary: 57000 },
  { id: "school-counselor", name: "School Counselor", medianSalary: 64000 },
  { id: "scientist-research", name: "Research Scientist", medianSalary: 105000 },
  { id: "security-guard", name: "Security Guard", medianSalary: 35000 },
  { id: "seo-specialist", name: "SEO Specialist", medianSalary: 65000 },
  { id: "social-media-manager", name: "Social Media Manager", medianSalary: 65000 },
  { id: "social-worker", name: "Social Worker", medianSalary: 55000 },
  { id: "software-engineer", name: "Software Engineer", medianSalary: 125000 },
  { id: "software-tester", name: "Software Tester", medianSalary: 70000 },
  { id: "sound-designer", name: "Sound Designer", medianSalary: 65000 },
  { id: "speech-pathologist", name: "Speech Pathologist", medianSalary: 90000 },
  { id: "statistician", name: "Statistician", medianSalary: 112000 },
  { id: "stockbroker", name: "Stockbroker", medianSalary: 90000 },
  { id: "structural-engineer", name: "Structural Engineer", medianSalary: 104000 },
  { id: "supply-chain-manager", name: "Supply Chain Manager", medianSalary: 120000 },
  { id: "surveyor", name: "Surveyor", medianSalary: 68000 },
  { id: "tailor", name: "Tailor", medianSalary: 36000 },
  { id: "tax-preparer", name: "Tax Preparer", medianSalary: 58000 },
  { id: "teacher-highschool", name: "High School Teacher", medianSalary: 65000 },
  { id: "technical-writer", name: "Technical Writer", medianSalary: 78000 },
  { id: "therapist-mental-health", name: "Mental Health Therapist", medianSalary: 60000 },
  { id: "therapist-occupational", name: "Occupational Therapist", medianSalary: 92000 },
  { id: "therapist-physical", name: "Physical Therapist", medianSalary: 98000 },
  { id: "tile-setter", name: "Tile Setter", medianSalary: 48000 },
  { id: "tour-guide", name: "Tour Guide", medianSalary: 36000 },
  { id: "translator", name: "Translator", medianSalary: 52000 },
  { id: "truck-driver", name: "Truck Driver", medianSalary: 52000 },
  { id: "tutor", name: "Tutor", medianSalary: 43000 },
  { id: "ui-ux-designer", name: "UI/UX Designer", medianSalary: 105000 },
  { id: "ultrasound-technician", name: "Ultrasound Technician", medianSalary: 78000 },
  { id: "veterinarian", name: "Veterinarian", medianSalary: 110000 },
  { id: "vet-tech", name: "Veterinary Technician", medianSalary: 38000 },
  { id: "videographer", name: "Videographer", medianSalary: 52000 },
  { id: "waiter", name: "Waiter", medianSalary: 30000 },
  { id: "web-developer", name: "Web Developer", medianSalary: 85000 },
  { id: "welder", name: "Welder", medianSalary: 50000 },
  { id: "writer-author", name: "Writer/Author", medianSalary: 69000 },
  { id: "zoologist", name: "Zoologist", medianSalary: 76000 }
];
